import Link from "next/link";

export default function ResetPasswordLandingPage() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-[#f5f3ee] px-6">
      <div className="w-full max-w-xl rounded-[32px] border border-black/8 bg-white px-8 py-10 text-center">
        <h1 className="text-3xl font-semibold text-slate-950">Use a backend-issued reset link</h1>
        <p className="mt-4 text-sm leading-7 text-slate-500">
          Password reset pages should be opened using the secure tokenized link
          generated by your backend service.
        </p>
        <Link
          href="/login"
          className="mt-8 inline-flex rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white"
        >
          Return to login
        </Link>
      </div>
    </div>
  );
}
